export const profile = {
  name: "Louis Chua Khai Yi",
  email: "yiclouis0702@gmail.com",
  github: "https://github.com/chuakhaiyi",
  linkedin: "https://www.linkedin.com/in/louis-chua-khai-yi",
  resume: "/Louis_Chua_Khai_Yi_Resume.pdf",
};

export const projects = [
  {
    slug: "formpilot", name: "FormPilot", category: "Personal project", date: "Offline document tool", mark: "F", cover: "formpilot",
    tagline: "From scanned forms to structured fields.",
    summary: "An offline tool for Malaysian students that extracts information from PDFs and images, flags form issues, and exports structured JSON.",
    stack: ["Python", "Tesseract OCR", "Streamlit", "FastAPI"],
    role: "Personal project", team: "Personal project", result: "Local application · source available",
    contribution: "I built FormPilot as a personal project for offline document extraction and validation for Malaysian students.",
    details: "FormPilot processes university, scholarship, and internship forms locally. Its Streamlit interface displays the detected document type, extracted fields, confidence indicators, validation issues, and OCR text, with a JSON download. A FastAPI interface exposes document extraction and local processing history; SQLite stores metadata only. The default document classifier uses deterministic rules, with an optional scikit-learn TF-IDF classifier trained from labelled examples. Docker Compose supports local setup. The included evaluation fixture is a smoke test, not a benchmark of accuracy on Malaysian forms.",
    challenge: "[ADD YOUR DEVELOPMENT CHALLENGE AND HOW YOU APPROACHED IT]",
    repo: "https://github.com/chuakhaiyi/FormPilot", source: "https://github.com/chuakhaiyi/FormPilot/blob/master/README.md",
  },
  {
    slug: "queuesense", name: "QueueSense", category: "Personal project", date: "Prediction system", mark: "Q", cover: "queuesense",
    tagline: "Know the wait before you go.",
    summary: "A campus queue-time prediction system that compares a location/hour baseline with a Random Forest model and exposes predictions through an API and dashboard.",
    stack: ["Python", "scikit-learn", "FastAPI", "Streamlit"],
    role: "Personal project", team: "Personal project", result: "Local application · source available",
    contribution: "I built QueueSense as a personal machine learning project, including the observation workflow, prediction API, evaluation route, and Streamlit dashboard.",
    details: "QueueSense records queue observations in a shared SQLite database, compares a simple location/hour baseline with a Random Forest model, and serves predictions through FastAPI. The Streamlit dashboard provides a view of observations, locations, predictions, and evaluation. The model falls back to the baseline until enough observations exist, and reports mean absolute error from collected data rather than claiming accuracy in advance. Docker support is included.",
    challenge: "[ADD YOUR DEVELOPMENT CHALLENGE AND HOW YOU APPROACHED IT]",
    repo: "https://github.com/chuakhaiyi/QueueSense", source: "https://github.com/chuakhaiyi/QueueSense/blob/main/README.md",
  },
  {
    slug: "ledge", name: "Ledge", category: "Personal project", date: "Windows application", mark: "L", cover: "ledge",
    tagline: "A little space for your thoughts.",
    summary: "A Windows sticky-note app that keeps notes at the edge of the screen, ready to peek or open without interrupting your workspace.",
    stack: ["C#", "WPF", ".NET 8", "Win32"],
    role: "Personal project", team: "Personal project", result: "Windows app · source available",
    contribution: "I built Ledge, a Windows notes application. It is my personal software project outside my AI coursework and team hackathons.",
    details: "Ledge supports edge docking, hover previews, floating notes, keyboard shortcuts, pinning and archiving. Notes stay on the PC in JSON storage, with a portable mode for carrying the app and its data together.",
    challenge: "[ADD YOUR DEVELOPMENT CHALLENGE AND HOW YOU APPROACHED IT]",
    repo: "https://github.com/chuakhaiyi/Ledge", source: "https://github.com/chuakhaiyi/Ledge/blob/master/README.md",
  },
  {
    slug: "suiroll", name: "Suiroll", category: "MUBA Hackathon", date: "06 September 2026", mark: "S", cover: "suiroll",
    tagline: "From spreadsheet to settlement.",
    summary: "A team-built contractor payroll workspace combining AI-assisted imports, human approval, and USDC payments on Sui testnet.",
    stack: ["React", "TypeScript", "Supabase", "Sui"],
    role: "Frontend UI", team: "4 people · 1 week", result: "Hackathon participant",
    contribution: "I was responsible for the frontend UI in our four-person team. We had one week to build before our pitch on 6 September. My main challenge was connecting the frontend and backend.",
    details: "The team project imports payroll spreadsheets, reviews payment inputs, prepares batches for wallet approval, and reconciles transfers. The repository describes a Sui testnet prototype, with React, TypeScript, Vinext, Tailwind CSS, Supabase, Gonka, and Sui tooling.",
    challenge: "Connecting the frontend UI to the backend. [ADD HOW YOU APPROACHED THE INTEGRATION]",
    repo: "https://github.com/DayDreamingLab/suirollpay", source: "https://github.com/DayDreamingLab/suirollpay/blob/main/README.md",
  },
  {
    slug: "medisync", name: "MediSync+", category: "UMHackathon", date: "May 2026", mark: "+", cover: "medisync",
    tagline: "Care beyond the discharge.",
    summary: "An AI-powered post-discharge healthcare companion with five agents for medication tracking, symptom triage, and risk prediction.",
    stack: ["Kotlin", "Jetpack Compose", "Room", "Hilt"],
    role: "UI development & bug fixes", team: "4 people", result: "Finalist · 11th place",
    contribution: "I led UI development and worked on bug fixes across our four-person team.",
    details: "Our team built a mobile healthcare companion around a five-agent AI system for medication tracking, symptom triage, and risk prediction. MediSync+ reached the UMHackathon finals and placed 11th.",
    challenge: "[ADD A SPECIFIC UI OR DEBUGGING CHALLENGE]",
    repo: "https://github.com/chuakhaiyi/MediSyncPlus-Finalist-", source: null,
  },
  {
    slug: "intelligent-cpd", name: "Intelligent CPD", category: "Imagine Hackathon", date: "June 2026", mark: "C", cover: "cpd",
    tagline: "The next thing worth learning.",
    summary: "An AI-powered professional development platform connecting client needs and advisor skill gaps to relevant learning paths.",
    stack: ["React", "TypeScript", "Express", "Supabase"],
    role: "UI & backend development", team: "Team project", result: "Taylor’s University · hackathon project",
    contribution: "I built UI and backend features for the advisor and admin dashboards.",
    details: "The platform has advisor and admin workspaces for CPD progress, client insights, course search, and learning paths. The backend validates AI-recommended course IDs against the course catalog before returning recommendations.",
    challenge: "[ADD YOUR DEVELOPMENT CHALLENGE AND APPROACH]",
    repo: "https://github.com/DayDreamingLab/Intelligent-CPD_Louis-Mutton", source: "https://github.com/DayDreamingLab/Intelligent-CPD_Louis-Mutton/blob/main/README.md",
  },
  {
    slug: "nextchapter", name: "NextChapter", category: "USAII Hackathon", date: "June 2026", mark: "N", cover: "nextchapter",
    tagline: "A clearer path to what’s next.",
    summary: "A Malaysia-focused agentic AI career planner generating pathway flowcharts with RM-based costs and feasibility scoring.",
    stack: ["TypeScript", "Next.js", "Supabase"],
    role: "UI fixes & backend development", team: "4 people", result: "Hackathon project",
    contribution: "I contributed UI fixes and backend development across our four-person team.",
    details: "Our team built a career pathway planner focused on Malaysia, with pathway flowcharts and feasibility scoring. The project brings local currency context to the planning process.",
    challenge: "[ADD YOUR DEVELOPMENT CHALLENGE AND APPROACH]",
    repo: null, source: null,
  },
] as const;

export const skills = [
  { title: "Languages", items: ["Python", "C", "C++", "Kotlin", "C#", "TypeScript"] },
  { title: "AI & data", items: ["PyTorch", "Scikit-learn", "Computer vision", "NLP", "Pandas", "NumPy"] },
  { title: "Applications", items: ["React", "Next.js", "Jetpack Compose", "WPF / .NET", "Node.js / Express", "Streamlit"] },
  { title: "Tools", items: ["Git", "Supabase", "Matplotlib", "Weka", "Excel"] },
];
